MDBoxLayout:
    md_bg_color: 1, 1, 0.9, 1
    padding: "5dp"
    MDLabel:
        text: "qwertyuiopaldkjfaldjkfaldjfa"
        font_size: "15dp"
        font_name: "fonts/Montserrat-Light.ttf"
        size_hint: None, 0.05
        width: app.caculate_width(self)
        halign: "center"
        opacity: 1
        canvas.before: 
            Color:
                rgba: 0.7, 1, 0.5, 1
            RoundedRectangle: 
                size: self.size
                pos: self.pos
                radius: [10, 0, 10, 10]