<AvatarItem>:
    avatar: ""
    icon: ""
    icon_color: [1, 1, 1, 1]
    icon_size: "39dp"
    theme_icon_color: "Custom"
    canvas.before:
        Color: 
            rgb: 242/255, 248/255, 247/255, 1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [50]
        RoundedRectangle:
            source: self.avatar
            #color: 1, 1, 1, 1
            size: self.size
            pos: self.pos
            radius: [50]